language: node_js
node_js:
- node
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq pandoc
script:
- npm run build
- npm run lint
- npm run test
- VERSION=$(node -p "require('./manifest.json').version") npm run lint-release
after_success:
- npm run coverage
deploy:
  provider: releases
  api_key:
    secure: UnT2Nwys8tZyWz2XmzTv20PHV3qI3M9lUWf43gAs4H9V5+dhjM/IjcXnMU1AHWyAB3mT+6137PbVGjYmJN/lyBDQw7S+yx0+MncMzSvm7redqL+erZd5M8VcSuWZ9tlVOW+UGbtyXWaX92vfFBdnzE//O61AI8Bjw/taKvGYet5RwVJ5T7SScSECssUXYzggRurmLVRTCqmfPH/jY0Xj0If3jLF9GcWg0Ar/mqPzUanfeTaVEVy3MgfRZQZWhyU0bJS2aDtuENBD5AvvsJWPW3+N5ujjz0uNXjDNKxdFY3circTz4FEV8bLiURXJNFGTcF/7iGgMZ+/utjBAUMBn96KMRR0LUyxtrmmPRmqDEOLEpvQ9JYwyt3L0D8i796p/QiMLYeFaJTkXgCG8brNA15ekVLxOJ5ZIBMagfsIdU4my4FClfjzSi3zfmCy/w66TxLz6jmO9Yg0HskKLxmb+uJsHG2AjfBbuAJWFkA2FiF/8k7ku4p446M7ZfBnsoL2v2Fr7XDLgujnW2zZ+YOvPU/hkZ2seOJuYl2gYXTz935L5G/FUbhWeyI6d8p5v9GBh9GtthEskk8wZZ6yMtUJx9XdiERjZXhv12fjavdHXujrfljPD/a/bKHeP63xwyYt4MYDXPqgQAjO+3LosOMytSAHdj4sIGU/SjGwVvksHaCM=
  file_glob: true
  file: ".releases/request_control-*.zip"
  on:
    repo: tumpio/requestcontrol
    tags: true
  skip_cleanup: true
after_deploy:
  - node ./bin/deploy.js